package isochrones.algorithm.statistics;

public enum Type {
  EXPANDED_NODES,
  EXPLORED_NODES,
  LOADED_NODES,
  REMOVED_NODES,
  REMAINING_NODES,
  EXPANDED_BOUNDARY_NODES,
  SKIPCONTINUOUS_EXPANDED_BOUNDARY_NODES,
  LOADED_CONTINUOUS_LINKS,
  ADDED_CONTINUOUS_LINKS,
  EXPLORED_CONTINUOUS_LINKS,
  LOADED_DISCRETE_LINKS,
  ADDED_DISCRETE_LINKS,
  LOCAL_EXPLORATION,
  JUNK_EXPLORATION,
  UNEXPLORED_LINKS,
  ADDED_REDUNDANT_CONTINUOUS_LINKS,
  ADDED_REDUNDANT_DISCRETE_LINKS,
  EXPLORED_SINGLE_DISCRETE_LINK,
  EXPLORED_HETERO_DISCRETE_LINKS, 
  EXPLORED_HOMO_DISCRETE_LINKS, 
  DENSITY_LOOKUP, 
  LOADED_LINKS_WITH_IER,
  LOADED_LINKS_WITH_INE, 
  PREEXPLORED_HOMO_SCHEDULELOOKUP,
  PREEXPLORED_HETERO_SCHEDULELOOKUP, EDIST_LOOKUP
}