package isochrones.algorithm.statistics;

public enum DBType {
  GET_CALENDAR_DATE,
  GET_CONTINUOUS_LINK,
  GET_BUS_LINK,
  GET_LINKS,
  GET_IER_LINKS,
  GET_DISCRETE_HOMO_COST,
  GET_DISCRETE_HETERO_COST,
  GET_CONTINUOUS_NODES,
  GET_NODES,
  GET_JUNKS_DISTANCES,
  GET_JUNKS, 
  GET_PARTITIONS,
  GET_REMAINING_DISTANCE,
  GET_COORDINATE, DENSITY_LOOKUP, 
  GET_INE_PRE_LINKS, // INE LINK during preexploration
  GET_INE_LINKS // INE LINKE during expansion
, EDIST_LOOKUP
}
