package isochrones.utils.entries;

public enum Detail {
  TOTAL,
  TOTAL_DB,
  NETWORK,
  SCHEDULE,
  RANGEQUERY,
  RANGEQUERY_MIN,
  RANGEQUERY_MAX,
  RANGEQUERY_LOAD,
  POINTQUERY,
  POINTQUERY_LOAD,
  POINTQUERY_PRE,
  LOCATIONQUERY,
  DENSITYQUERY,
  SCHEDULEHOMO,
  SCHEDULEHETERO,
  EXPANDED_VERTICES,
  EXPLORED_VERTICES
}
